name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Build extension
      run: npm run build
      
    - name: Verify extension structure
      run: |
        echo "Verifying required extension files exist in dist/..."
        test -f dist/manifest.json || (echo "manifest.json missing" && exit 1)
        test -f dist/popup.html || (echo "popup.html missing" && exit 1)
        test -f dist/popup.js || (echo "popup.js missing" && exit 1)
        test -f dist/content.js || (echo "content.js missing" && exit 1)
        test -d dist/icons || (echo "icons directory missing" && exit 1)
        echo "✅ All required extension files present"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-build-${{ github.sha }}
        path: dist/
        retention-days: 7 